theme = "deluxe_dark"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
# show open buffers: bufferline = "multiple"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"
center = ["workspace-diagnostics"]

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.soft-wrap]
enable = true

[keys.normal]
# Colemak movements and remap of conflicted keys
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"

# Move ten lines up or down on shifted movement key
E = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down", 
     "move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"] 

I = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up", 
     "move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"] 

# Mark til end of line / start of line
N = ["extend_to_line_start"]
O = ["extend_to_line_end"]

h = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
H = "insert_at_line_start"

l = "open_below"
L = "open_above"

# Search for word under cursor
"k" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"K" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

j = "search_next"
J = "search_prev"
"C-j" = "join_selections"
"C-J" = "join_selections_space"

# vim-like motions without expanding selection
# W = ["move_next_word_start", "collapse_selection"]
# B = ["move_prev_word_start", "collapse_selection"]

# extending movement
"C-w" = "extend_next_word_start"
"C-W" = "extend_next_long_word_start"
"C-b" = "extend_prev_word_start"
"C-B" = "extend_prev_long_word_start"
"C-n" = "extend_to_first_nonwhitespace"
"C-N" = "extend_to_line_start"
"C-o" = "extend_to_line_end"
"C-O" = "extend_to_line_end_newline"
# "C-t" = "extend_till_next_char"
"C-T" = "extend_till_prev_char"
"C-f" = "extend_next_char"
"C-F" = "extend_prev_char"
"C-p" = "extend_parent_node_end"
"C-P" = "extend_parent_node_start"

"C-e" = "shrink_selection"
"C-i" = "expand_selection"
"<" = "shrink_selection"
">" = "expand_selection"

# macOS movements
"A-left" = "move_prev_word_start"
"A-right" = "move_next_word_end"
"S-A-left" = "extend_prev_word_start"
"S-A-right" = "extend_next_word_end"
"S-left" = "extend_char_left"
"S-right" = "extend_char_right"
"S-up" = "extend_line_up"
"S-down" = "extend_line_down"
"C-S-down" = "copy_selection_on_next_line"
"C-S-up" = "copy_selection_on_prev_line"
# TODO: Remap cmd in iterm to allow for command shortcuts
# "M-left" jump to first non whitespace in line
# "M-right" jump to end of line
# with shift: extend selection to ...
# "C-M-left" collapse code
# "C-M-right" expand code

# macOS-like deletions
"backspace" = "delete_char_backward"
"S-backspace" = "delete_char_forward"
"A-backspace" = "delete_word_backward"
"S-A-backspace" = "delete_word_forward"
"C-backspace" = "delete_selection"

# Tab-indentation
"tab" = "indent"
"S-tab" = "unindent"

# Insert mode toggle
"C-h" = "insert_mode"

# vim-impaired style movement for navigating buffers
"[" = { b = "goto_previous_buffer", s = "select_prev_sibling" }
"]" = { b = "goto_next_buffer", s = "select_next_sibling" }

# Use clipboard instead of registers
y = ["yank_main_selection_to_clipboard", "collapse_selection"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"

# Other remaps
z = "undo"
Z = "redo"

u = "switch_to_lowercase"
U = "switch_to_uppercase"
"C-u" = "switch_case"

C = "toggle_comments"
"C-c" = "copy_selection_on_next_line"
"C-C" = "copy_selection_on_prev_line"

"'" = "select_regex"

# "-s" = ":write-all"
# Jump Mode keys
s = "goto_word"

G = "goto_file_end"
# TODO: Remap "Select Regex" keys

[keys.normal.space.z]
# Colemak movements
n = "align_view_top"
e = "scroll_down"
i = "scroll_up"
o = "align_view_bottom"
c = "align_view_center"
z = "align_view_center"

[keys.normal.g]
# Colemak movements
n = "goto_first_nonwhitespace"
i = "goto_file_start"
o = "goto_line_end"

I = "goto_implementation"

[keys.select.g]
# Colemak movements
n = "extend_to_first_nonwhitespace"
# i = "extend_to_file_start"
o = "extend_to_line_end"

[keys.normal.space]
"," = "last_picker"
space = "file_picker"
p = "paste_after"
P = "paste_before"
y = "yank"
Y = "yank_joined"
R = "replace_with_yanked"
e = ":write-quit-all"

[keys.normal.space.w]
# Colemak movements
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"

[keys.normal.A-w]
# Colemak movements and remap of conflicted keys
n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"

[keys.normal.D]
# vim-like delete mode
w = "delete_word_forward"
W = ["move_next_long_word_start", "delete_selection", "collapse_selection", "normal_mode"]
b = "delete_word_backward"
B = ["move_prev_word_start", "delete_selection", "collapse_selection", "normal_mode"]
n = "kill_to_line_start"
o = "kill_to_line_end"
x = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
d = "delete_selection_noyank"
y = "delete_selection"

[keys.normal.Y]
# vim-like yanking
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
b = ["move_prev_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
B = ["move_prev_long_word_start", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
x = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
y = "yank_main_selection_to_clipboard"
d = ["yank_main_selection_to_clipboard", "delete_selection"]
j = "yank_joined_to_clipboard"

[keys.insert]
# Normal mode toggle
"C-h" = "normal_mode" 

# macOS movements
"A-left" = "move_prev_word_start"
"A-right" = "move_next_word_end"
"S-A-left" = "extend_prev_word_start"
"S-A-right" = "extend_next_word_end"

# macOS-like deletions
"backspace" = "delete_char_backward"
"S-backspace" = "delete_char_forward"
"A-backspace" = "delete_word_backward"
"S-A-backspace" = "delete_word_forward"
"C-backspace" = "delete_selection"

[keys.select]
# Colemak movements and remap of conflicted keys
n = "extend_char_left"
e = "extend_line_down"
i = "extend_line_up"
o = "extend_char_right"
N = "extend_to_first_nonwhitespace"
E = "no_op"
I = "no_op"
O = "extend_to_line_end"

h = "insert_mode"
H = "insert_at_line_start"

l = "open_below"
L = "open_above"

j = "search_next"
J = "search_prev"


