# Author : Antonius Naumann <git@antonius.dev> @antoniusnaumann
# Deluxe Dark
# A cyan & orange theme for helix inspired by iTerm 2's default color scheme. Feel free to contribute

# Primary Color: light-cyan
# Secondary Color: orange
# Highlight Text: very-light-yellow
# Accent Color: light-blue
# Special Accent Color: light-green (do not use for regular text)
#
# General Philosophy: light colors for text, normal colors for UI elements. Configure your terminal accordingly!

# Jump Mode colors
"ui.virtual.jump-label" = { fg = "light-green", modifiers = ["bold"] }

"attribute" = "light-green"

"type" = "light-blue"
"type.builtin" = { fg = "light-blue", modifiers = ["italic"] }
"type.return" = "light-blue"
"type.parameter" = "light-magenta"
"type.enum.variant" = "very-light-yellow"
"constructor" = "light-blue"

"constant" = "light-yellow"
# "constant.builtin" = {} # .boolean
"constant.builtin.boolean" = "light-yellow"
"constant.character" = "light-yellow"
"constant.character.escape" = "light-green"
"constant.numeric" = "light-yellow"
"string" = "yellow"
"string.regexp" = "cyan"
"string.special" = { fg = "yellow", modifiers = ["underlined"] } #.path / .url / .symbol

"comment" = "gray" # .line
# "comment.block" = {} # .documentation
"variable" = "Gray 120" 
"variable.builtin" = "light-cyan"
"variable.parameter" = "very-light-orange"
"variable.other.member" = "very-light-yellow"
"label" = { fg = "light-magenta", modifiers = ["italic"] }

"keyword" = "light-cyan" # .operator / .directive / .function
"keyword.return" = "light-red"
"keyword.exception" = "light-red"

"operator" = "light-magenta"
"punctuation.delimiter" = "Gray 100"
"punctuation.bracket" = "Gray 100"

"function" = "very-light-yellow"
"function.declaration" = "#EFEFEF"
"function.macro" = { fg = "light-cyan", modifiers = ["italic"] }
"function.builtin" = "light-cyan"
"function.special" = "light-cyan"
#"function.declaration.method" = { fg = "lightest", modifiers = ["bold"] } #depends on #4892
"tag" = "light-blue"
"special" = "light-magenta"
"namespace" = { fg = "Gray 110" }

# used in theming
# "markup" = {} # .normal / .quote / .raw
# "markup.normal" = {} # .completion / .hover
"markup.bold" = {  modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.heading" = { fg = "light-cyan", modifiers = ["bold"] } # .marker / .1 / .2 / .3 / .4 / .5 / .6
"markup.list" = "magenta" # .unnumbered / .numbered
"markup.list.numbered" = "light-cyan"
"markup.list.unnumbered" = "light-cyan"
# "markup.link" = "green"
"markup.link.url" = { fg = "magenta", modifiers = ['italic', 'underlined'] }
"markup.link.text" = "light-blue"
"markup.link.label" = "light-yellow"
"markup.quote" = "magenta"
"markup.raw" = "magenta"
"markup.raw.inline" = "light-cyan" # .completion / .hover
"markup.raw.block" = "#EB83E2"

"diff.plus" = "green"
"diff.minus" = "ged"
"diff.delta" = "blue"

# ui specific
"ui.background" = { bg = "background" } # .separator
"ui.statusline" = { fg = "white", bg = "black" } # .inactive / .normal / .insert / .select
"ui.statusline.normal" = { fg = "lightest", bg = "darker"}
"ui.statusline.insert" = { fg = "lightest", bg = "blue_accent" }
"ui.statusline.select" = { fg = "lightest", bg = "orange_accent" }

"ui.cursor" = { modifiers = ["reversed"] } # .insert / .select / .match / .primary
"ui.cursor.match" = { bg = "Gray 70" } # .insert / .select / .match / .primary
"ui.selection" = { bg = "Gray 50" } # .primary
"ui.selection.primary" = { bg = "Gray 80" }

"ui.cursorline" = { bg = "Gray 20" }
"ui.linenr" = "Gray 70"
"ui.linenr.selected" = "Gray 110"

"ui.popup" = { fg = "Foreground", bg = "Gray 20" } # .info
"ui.window" = { fg = "Gray 50" }
"ui.help" = { fg = "Foreground", bg = "Gray 20" }
"ui.menu" = { fg = "Foreground", bg = "Gray 20" } # .selected
"ui.menu.selected" = { fg = "White", bg = "Selection" } # .selected
# Calculated as #ffffff with 30% opacity
"ui.menu.scroll" = { fg = "#dfdfdf" }

"ui.text" = "white" # .focus / .info
"ui.text.focus" = { fg = "Cursor", bg = "Gray 80" }

"ui.virtual" = "Gray 80" # .whitespace
# "ui.virtual.ruler" = { bg = "darker"}

"hint" = "cyan"
"info" = "blue"
"warning" = "light-yellow"
"error" = "red"

"diagnostic.hint" = { underline = { color = "cyan", style = "line" } }
"diagnostic.info" = { underline = { color = "blue", style = "line" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "line" } }
"diagnostic.error" = { underline = { color = "red", style = "line" } }

[palette]
"Gray 120" = "#d9d9d9"
"Gray 110" = "#c2c2c2"
"Gray 100" = "#a0a0a0"
"Gray 90" = "#898989"
"Gray 80" = "#767676"
"Gray 70" = "#5d5d5d"
"Gray 60" = "#484848"
"Gray 50" = "#383838"
"Gray 40" = "#333333"
"Gray 30" = "#2d2d2d"
"Gray 20" = "#292929"

"very-light-orange" = "#edc86d"
"very-light-yellow" = "#f0eca3"

"Selection" = "#b3d7ff"
"Cursor" = "#fefffe"
